services:
  kaggle:
    build: . 
    ports:
      - 8888:8888
      - 5902:5901
    command:
       /root/startup.sh
    volumes:
      - ./notebooks:/notebooks
      - ./startup.sh:/root/startup.sh
      
